import type { ActionId, GovernanceTarget } from "./types.js";

export type ActionCatalogEntry = {
  id: ActionId;
  target: GovernanceTarget | "timelock";
  title: string;
  /** Arg keys expected by encodeOwnerAction. */
  argKeys: string[];
  /** Plan 13 / production: prefer Safe (+ optional TimelockController). */
  critical: boolean;
  notes: string;
};

export const ACTION_CATALOG: ActionCatalogEntry[] = [
  {
    id: "ownable.transferOwnership",
    target: "ownable",
    title: "Transfer Ownable ownership",
    argKeys: ["newOwner"],
    critical: true,
    notes: "Use to hand contracts to Protocol Safe or TimelockController.",
  },
  {
    id: "gameRegistry.setMinDelay",
    target: "gameRegistry",
    title: "GameRegistry — set minDelay",
    argKeys: ["newDelay"],
    critical: true,
    notes: "Production should use non-zero delay (seconds).",
  },
  {
    id: "gameRegistry.setEmergencyGuardian",
    target: "gameRegistry",
    title: "GameRegistry — set emergency guardian",
    argKeys: ["guardian"],
    critical: true,
    notes: "Guardian may emergencyDeactivate only — not ownership.",
  },
  {
    id: "gameRegistry.scheduleActivation",
    target: "gameRegistry",
    title: "GameRegistry — schedule template activation",
    argKeys: ["templateId"],
    critical: true,
    notes: "Contract-internal timelock; executeActivation after eta.",
  },
  {
    id: "gameRegistry.executeActivation",
    target: "gameRegistry",
    title: "GameRegistry — execute template activation",
    argKeys: ["templateId"],
    critical: true,
    notes: "Permissionless after eta; Safe may still submit for ops clarity.",
  },
  {
    id: "gameRegistry.scheduleDeactivation",
    target: "gameRegistry",
    title: "GameRegistry — schedule template deactivation",
    argKeys: ["templateId"],
    critical: true,
    notes: "Stops NEW sessions only after execute.",
  },
  {
    id: "gameRegistry.executeDeactivation",
    target: "gameRegistry",
    title: "GameRegistry — execute template deactivation",
    argKeys: ["templateId"],
    critical: true,
    notes: "Permissionless after eta.",
  },
  {
    id: "gameRegistry.cancelOperation",
    target: "gameRegistry",
    title: "GameRegistry — cancel pending op",
    argKeys: ["templateId"],
    critical: true,
    notes: "Owner cancels before execute.",
  },
  {
    id: "protocolFeeVault.scheduleTreasuryUpdate",
    target: "protocolFeeVault",
    title: "FeeVault — schedule Treasury Safe update",
    argKeys: ["newTreasury"],
    critical: true,
    notes: "Treasury changes require Safe + contract timelock.",
  },
  {
    id: "protocolFeeVault.executeTreasuryUpdate",
    target: "protocolFeeVault",
    title: "FeeVault — execute Treasury Safe update",
    argKeys: [],
    critical: true,
    notes: "After minDelay from schedule.",
  },
  {
    id: "protocolFeeVault.cancelTreasuryUpdate",
    target: "protocolFeeVault",
    title: "FeeVault — cancel treasury update",
    argKeys: [],
    critical: true,
    notes: "Owner cancel before execute.",
  },
  {
    id: "protocolFeeVault.setMinDelay",
    target: "protocolFeeVault",
    title: "FeeVault — set minDelay",
    argKeys: ["newDelay"],
    critical: true,
    notes: "Governance delay for treasury updates.",
  },
  {
    id: "protocolFeeVault.setEmergencyGuardian",
    target: "protocolFeeVault",
    title: "FeeVault — set emergency guardian",
    argKeys: ["guardian"],
    critical: true,
    notes: "Guardian may pause sweeps; cannot sweep.",
  },
  {
    id: "protocolFeeVault.setDepositor",
    target: "protocolFeeVault",
    title: "FeeVault — set depositor",
    argKeys: ["depositor", "allowed"],
    critical: true,
    notes: "Authorize ArenaVault (or revoke).",
  },
  {
    id: "protocolFeeVault.sweep",
    target: "protocolFeeVault",
    title: "FeeVault — sweep to Treasury Safe",
    argKeys: ["amount", "periodRoot", "sessionRange"],
    critical: true,
    notes: "Owner-only; destination is configured treasurySafe.",
  },
  {
    id: "proofBatchRegistry.schedulePublisherUpdate",
    target: "proofBatchRegistry",
    title: "ProofBatchRegistry — schedule publisher replace",
    argKeys: ["newPublisher"],
    critical: true,
    notes: "Contract-internal timelock.",
  },
  {
    id: "proofBatchRegistry.executePublisherUpdate",
    target: "proofBatchRegistry",
    title: "ProofBatchRegistry — execute publisher replace",
    argKeys: [],
    critical: true,
    notes: "After minDelay.",
  },
  {
    id: "proofBatchRegistry.cancelPublisherUpdate",
    target: "proofBatchRegistry",
    title: "ProofBatchRegistry — cancel publisher replace",
    argKeys: [],
    critical: true,
    notes: "Owner cancel before execute.",
  },
  {
    id: "proofBatchRegistry.setMinDelay",
    target: "proofBatchRegistry",
    title: "ProofBatchRegistry — set minDelay",
    argKeys: ["newDelay"],
    critical: true,
    notes: "Publisher replace delay.",
  },
  {
    id: "arenaVault.pause",
    target: "arenaVault",
    title: "ArenaVault — pause",
    argKeys: [],
    critical: true,
    notes: "Emergency containment; does not move funds.",
  },
  {
    id: "arenaVault.unpause",
    target: "arenaVault",
    title: "ArenaVault — unpause",
    argKeys: [],
    critical: true,
    notes: "Resume after incident clearance.",
  },
  {
    id: "arenaVault.setSettlementHub",
    target: "arenaVault",
    title: "ArenaVault — set settlement hub",
    argKeys: ["hub"],
    critical: true,
    notes: "Privileged settlement path.",
  },
  {
    id: "arenaVault.setFeeTreasury",
    target: "arenaVault",
    title: "ArenaVault — set fee treasury",
    argKeys: ["treasury"],
    critical: true,
    notes: "V2: typically ProtocolFeeVault address.",
  },
  {
    id: "arenaVault.setSessionRelayer",
    target: "arenaVault",
    title: "ArenaVault — set session relayer",
    argKeys: ["relayer"],
    critical: true,
    notes: "Hot key allowlist — rotate carefully.",
  },
  {
    id: "verifierRouter.setVerifier",
    target: "verifierRouter",
    title: "VerifierRouter — set verifier",
    argKeys: ["policyId", "verifier"],
    critical: true,
    notes: "Verifier policy change — production Safe + delay.",
  },
  {
    id: "verifierRouter.setDefaultPolicyId",
    target: "verifierRouter",
    title: "VerifierRouter — set default policy",
    argKeys: ["policyId"],
    critical: true,
    notes: "Default settlement proof policy.",
  },
  {
    id: "signatureQuorumVerifier.setAttestor",
    target: "signatureQuorumVerifier",
    title: "QuorumVerifier — set attestor",
    argKeys: ["attestor", "allowed"],
    critical: true,
    notes: "Attestor set changes are governance-critical.",
  },
  {
    id: "signatureQuorumVerifier.setMinSignatures",
    target: "signatureQuorumVerifier",
    title: "QuorumVerifier — set min signatures",
    argKeys: ["minSigs"],
    critical: true,
    notes: "Quorum threshold.",
  },
  {
    id: "settlementHubV3.setRouter",
    target: "settlementHubV3",
    title: "SettlementHubV3 — set router",
    argKeys: ["router"],
    critical: true,
    notes: "Routes settlement verification.",
  },
  {
    id: "settlementHubV3.setProofBatchRegistry",
    target: "settlementHubV3",
    title: "SettlementHubV3 — set proof batch registry",
    argKeys: ["registry", "requireBatch"],
    critical: true,
    notes: "Optional batch gate.",
  },
  {
    id: "settlementHubV3.setMaxTotalRake",
    target: "settlementHubV3",
    title: "SettlementHubV3 — set max total rake",
    argKeys: ["maxRake"],
    critical: true,
    notes: "Rake cap — public policy change.",
  },
  {
    id: "timelock.schedule",
    target: "timelock",
    title: "TimelockController — schedule (raw)",
    argKeys: ["target", "value", "data", "predecessor", "salt", "delay"],
    critical: true,
    notes: "Prefer mode=timelockController on other actions.",
  },
  {
    id: "timelock.execute",
    target: "timelock",
    title: "TimelockController — execute (raw)",
    argKeys: ["target", "value", "data", "predecessor", "salt"],
    critical: true,
    notes: "After OZ TimelockController delay.",
  },
  {
    id: "timelock.cancel",
    target: "timelock",
    title: "TimelockController — cancel",
    argKeys: ["id"],
    critical: true,
    notes: "Cancel scheduled operation by id.",
  },
];

export function getCatalogEntry(id: ActionId): ActionCatalogEntry | undefined {
  return ACTION_CATALOG.find((e) => e.id === id);
}
