#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const depDir = join(root, "deployments");

const defaults = {
  anvil: {
    chainId: 31337,
    usdc: "0x0000000000000000000000000000000000000000",
    symbol: "mUSDC",
    decimals: 6,
    isTestAsset: true,
    faucetEnabled: true,
    protocolVersion: "1.0.0-anvil",
    vrfCoordinator: null,
    vrfKeyHash: null,
  },
  baseSepolia: {
    chainId: 84532,
    usdc: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
    symbol: "USDC",
    decimals: 6,
    isTestAsset: false,
    faucetEnabled: false,
    protocolVersion: "1.0.0-sepolia",
    vrfCoordinator: "0x5C210eF41CD1a72a13DcB20c28948D40729fEFFb",
    vrfKeyHash: "0x9e1344a1247c8a1785d0a4681a27152bffdb43666ae28ee20d8c6dff7f9c1a30",
  },
  base: {
    chainId: 8453,
    usdc: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    symbol: "USDC",
    decimals: 6,
    isTestAsset: false,
    faucetEnabled: false,
    protocolVersion: "1.0.0",
    vrfCoordinator: "0xd5D517aBE5cF79B7e95eC98dB0f0277788aFF634",
    vrfKeyHash: null,
  },
};

function load(network) {
  const path = join(depDir, `${network}.json`);
  const d = defaults[network];
  let file = {};
  if (existsSync(path)) file = JSON.parse(readFileSync(path, "utf8"));
  const hex = (v) => (typeof v === "string" && /^0x[a-fA-F0-9]+$/.test(v) ? v : null);

  const isTestAsset = network === "base" ? false : Boolean(file.isTestAsset ?? d.isTestAsset);
  const faucetEnabled = network === "base" ? false : Boolean(file.faucetEnabled ?? d.faucetEnabled);
  const symbol = network === "base" ? "USDC" : (file.symbol ?? d.symbol);

  if (network === "base" && (file.isTestAsset || file.symbol === "mUSDC")) {
    throw new Error("MockUSDC / test assets are forbidden on Base mainnet");
  }

  return {
    chainId: file.chainId ?? d.chainId,
    usdc: file.usdc ?? d.usdc,
    symbol,
    decimals: Number(file.decimals ?? d.decimals),
    isTestAsset,
    faucetEnabled,
    arenaVault: hex(file.arenaVault),
    arenaVaultV1: hex(file.arenaVaultV1),
    arenaAccountFactory: hex(file.arenaAccountFactory),
    arenaAccountImplementation: hex(file.arenaAccountImplementation),
    tableRegistry: hex(file.tableRegistry),
    settlementHub: hex(file.settlementHub),
    settlementHubV1: hex(file.settlementHubV1),
    checkpointRegistry: hex(file.checkpointRegistry),
    randomnessCoordinator: hex(file.randomnessCoordinator),
    feeTreasury: hex(file.feeTreasury),
    deploymentBlock: String(file.deploymentBlock ?? 0),
    protocolVersion: file.protocolVersion ?? d.protocolVersion,
    vrfCoordinator: hex(file.vrfCoordinator) ?? d.vrfCoordinator,
    vrfKeyHash: hex(file.vrfKeyHash) ?? d.vrfKeyHash,
  };
}

const addr = (v) => (v ? `"${v}" as HexAddress` : "null");
const hash = (v) => (v ? `"${v}" as \`0x\${string}\`` : "null");

const networks = ["anvil", "baseSepolia", "base"];
const blocks = networks
  .map((n) => {
    const e = load(n);
    return `  ${n}: {
    chainId: ${e.chainId},
    usdc: "${e.usdc}" as HexAddress,
    symbol: "${e.symbol}",
    decimals: ${e.decimals},
    isTestAsset: ${e.isTestAsset},
    faucetEnabled: ${e.faucetEnabled},
    arenaVault: ${addr(e.arenaVault)},
    arenaVaultV1: ${addr(e.arenaVaultV1)},
    arenaAccountFactory: ${addr(e.arenaAccountFactory)},
    arenaAccountImplementation: ${addr(e.arenaAccountImplementation)},
    tableRegistry: ${addr(e.tableRegistry)},
    settlementHub: ${addr(e.settlementHub)},
    settlementHubV1: ${addr(e.settlementHubV1)},
    checkpointRegistry: ${addr(e.checkpointRegistry)},
    randomnessCoordinator: ${addr(e.randomnessCoordinator)},
    feeTreasury: ${addr(e.feeTreasury)},
    deploymentBlock: BigInt(${e.deploymentBlock}),
    protocolVersion: "${e.protocolVersion}",
    vrfCoordinator: ${addr(e.vrfCoordinator)},
    vrfKeyHash: ${hash(e.vrfKeyHash)},
  }`;
  })
  .join(",\n");

const out = `/**
 * AUTO-GENERATED by \`pnpm --filter @mozetto/chain-manifest codegen\`.
 * Do not edit by hand — update deployments/*.json and re-run codegen.
 */

export type HexAddress = \`0x\${string}\`;

export type NetworkKey = "anvil" | "baseSepolia" | "base";

export type ChainManifestEntry = {
  chainId: number;
  usdc: HexAddress;
  symbol: string;
  decimals: number;
  isTestAsset: boolean;
  faucetEnabled: boolean;
  arenaVault: HexAddress | null;
  arenaVaultV1: HexAddress | null;
  arenaAccountFactory: HexAddress | null;
  arenaAccountImplementation: HexAddress | null;
  tableRegistry: HexAddress | null;
  settlementHub: HexAddress | null;
  settlementHubV1: HexAddress | null;
  checkpointRegistry: HexAddress | null;
  randomnessCoordinator: HexAddress | null;
  feeTreasury: HexAddress | null;
  deploymentBlock: bigint;
  protocolVersion: string;
  /** Chainlink VRF v2.5 coordinator — verify before deploy */
  vrfCoordinator: HexAddress | null;
  vrfKeyHash: \`0x\${string}\` | null;
};

export const chainManifest = {
${blocks},
} as const satisfies Record<NetworkKey, ChainManifestEntry>;
`;

writeFileSync(join(root, "src/generated.ts"), out);
console.log(
  "Wrote src/generated.ts from",
  readdirSync(depDir).filter((f) => f.endsWith(".json")),
);
