/**
 * AUTO-GENERATED by `pnpm --filter @mozetto/chain-manifest codegen`.
 * Do not edit by hand — update deployments/*.json and re-run codegen.
 */

export type HexAddress = `0x${string}`;

export type NetworkKey = "anvil" | "baseSepolia" | "base";

export type ChainManifestEntry = {
  chainId: number;
  usdc: HexAddress;
  symbol: string;
  decimals: number;
  isTestAsset: boolean;
  faucetEnabled: boolean;
  arenaVault: HexAddress | null;
  arenaVaultV1: HexAddress | null;
  arenaAccountFactory: HexAddress | null;
  arenaAccountImplementation: HexAddress | null;
  tableRegistry: HexAddress | null;
  gameRegistry: HexAddress | null;
  sessionLifecycle: HexAddress | null;
  protocolFeeVault: HexAddress | null;
  settlementHub: HexAddress | null;
  settlementHubV1: HexAddress | null;
  /** Explicit V2 hub when settlementHub points at V3 (or null until deploy) */
  settlementHubV2: HexAddress | null;
  /** WP-063 FinalSettlementV3 hub (null until deploy) */
  settlementHubV3: HexAddress | null;
  /** WP-063 VerifierRouter */
  verifierRouter: HexAddress | null;
  /** WP-063 SignatureQuorumVerifier */
  signatureQuorumVerifier: HexAddress | null;
  checkpointRegistry: HexAddress | null;
  randomnessCoordinator: HexAddress | null;
  randomnessBeacon: HexAddress | null;
  /** WP-053 Chainlink VRF v2.5 adapter (null until Sepolia deploy) */
  chainlinkVrfAdapter: HexAddress | null;
  /** WP-062 global proof-batch registry (null until deploy) */
  proofBatchRegistry: HexAddress | null;
  feeTreasury: HexAddress | null;
  deploymentBlock: bigint;
  protocolVersion: string;
  /** Chainlink VRF v2.5 coordinator — verify before deploy */
  vrfCoordinator: HexAddress | null;
  vrfKeyHash: `0x${string}` | null;
};

export const chainManifest = {
  anvil: {
    chainId: 31337,
    usdc: "0x499AA73A1D27e54B33E7DB05ffd22854EC70257E" as HexAddress,
    symbol: "mUSDC",
    decimals: 6,
    isTestAsset: true,
    faucetEnabled: true,
    arenaVault: "0x834Ea01e45F9b5365314358159d92d134d89feEb" as HexAddress,
    arenaVaultV1: "0x8CeA85eC7f3D314c4d144e34F2206C8Ac0bbadA1" as HexAddress,
    arenaAccountFactory: "0x59c7D03d2E9893FB7bAa89dA50a9452e1e9B8b90" as HexAddress,
    arenaAccountImplementation: "0x90E75f390332356426B60FB440DF23f860F6A113" as HexAddress,
    tableRegistry: "0x10537D7bD661C9c34F547b38EC662D6FD482Ae95" as HexAddress,
    gameRegistry: "0xBD2fe040D03EB1d1E5A151fbcc19A03333223019" as HexAddress,
    sessionLifecycle: "0xfb6dAB6200b8958C2655C3747708F82243d3F32E" as HexAddress,
    protocolFeeVault: "0x7A5EC257391817ef241ef8451642cC6b222d4f8C" as HexAddress,
    settlementHub: "0x04F75a27cE2FDC591C71a88f1EcaC7e5Ce44f5Fc" as HexAddress,
    settlementHubV1: "0x29023DE63D7075B4cC2CE30B55f050f9c67548d4" as HexAddress,
    settlementHubV2: "0x0dEe24C99e8dF7f0E058F4F48f228CC07DB704Fc" as HexAddress,
    settlementHubV3: "0x04F75a27cE2FDC591C71a88f1EcaC7e5Ce44f5Fc" as HexAddress,
    verifierRouter: "0xCC5Bc84C3FDbcF262AaDD9F76652D6784293dD9e" as HexAddress,
    signatureQuorumVerifier: "0xFcCa971FE9Ee20C1Cf22596E700aA993D8fD19c5" as HexAddress,
    checkpointRegistry: "0x798f111c92E38F102931F34D1e0ea7e671BDBE31" as HexAddress,
    randomnessCoordinator: "0xabebE9a2D62Af9a89E86EB208b51321e748640C3" as HexAddress,
    randomnessBeacon: "0xf42Ec71A4440F5e9871C643696DD6Dc9a38911F8" as HexAddress,
    chainlinkVrfAdapter: null,
    proofBatchRegistry: "0xD73bAb8F06DB28c87932571f87D0D2C0FDF13D94" as HexAddress,
    feeTreasury: "0x9a61916C0b312F5cD1150596f117A092166ed1ad" as HexAddress,
    deploymentBlock: BigInt(4051),
    protocolVersion: "2.0.0-anvil",
    vrfCoordinator: null,
    vrfKeyHash: null,
  },
  baseSepolia: {
    chainId: 84532,
    usdc: "0x036CbD53842c5426634e7929541eC2318f3dCF7e" as HexAddress,
    symbol: "USDC",
    decimals: 6,
    isTestAsset: false,
    faucetEnabled: false,
    arenaVault: null,
    arenaVaultV1: null,
    arenaAccountFactory: null,
    arenaAccountImplementation: null,
    tableRegistry: null,
    gameRegistry: null,
    sessionLifecycle: null,
    protocolFeeVault: null,
    settlementHub: null,
    settlementHubV1: null,
    settlementHubV2: null,
    settlementHubV3: null,
    verifierRouter: null,
    signatureQuorumVerifier: null,
    checkpointRegistry: null,
    randomnessCoordinator: null,
    randomnessBeacon: null,
    chainlinkVrfAdapter: null,
    proofBatchRegistry: null,
    feeTreasury: null,
    deploymentBlock: BigInt(0),
    protocolVersion: "2.0.0-sepolia",
    vrfCoordinator: "0x5C210eF41CD1a72de73bF76eC39637bB0d3d7BEE" as HexAddress,
    vrfKeyHash: "0x9e1344a1247c8a1785d0a4681a27152bffdb43666ae5bf7d14d24a5efd44bf71" as `0x${string}`,
  },
  base: {
    chainId: 8453,
    usdc: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" as HexAddress,
    symbol: "USDC",
    decimals: 6,
    isTestAsset: false,
    faucetEnabled: false,
    arenaVault: null,
    arenaVaultV1: null,
    arenaAccountFactory: null,
    arenaAccountImplementation: null,
    tableRegistry: null,
    gameRegistry: null,
    sessionLifecycle: null,
    protocolFeeVault: null,
    settlementHub: null,
    settlementHubV1: null,
    settlementHubV2: null,
    settlementHubV3: null,
    verifierRouter: null,
    signatureQuorumVerifier: null,
    checkpointRegistry: null,
    randomnessCoordinator: null,
    randomnessBeacon: null,
    chainlinkVrfAdapter: null,
    proofBatchRegistry: null,
    feeTreasury: null,
    deploymentBlock: BigInt(0),
    protocolVersion: "2.0.0-mainnet-restricted",
    vrfCoordinator: "0xd5D517aBE5cF79B7e95eC98dB0f0277788aFF634" as HexAddress,
    vrfKeyHash: "0x00b81b5a830cb0a4009fbd8904de511e28631e62ce5ad231373d3cdad373ccab" as `0x${string}`,
  },
} as const satisfies Record<NetworkKey, ChainManifestEntry>;
