/**
 * AUTO-GENERATED by `pnpm --filter @mozetto/chain-manifest codegen`.
 * Do not edit by hand — update deployments/*.json and re-run codegen.
 */

export type HexAddress = `0x${string}`;

export type NetworkKey = "anvil" | "baseSepolia" | "base";

export type ChainManifestEntry = {
  chainId: number;
  usdc: HexAddress;
  symbol: string;
  decimals: number;
  isTestAsset: boolean;
  faucetEnabled: boolean;
  arenaVault: HexAddress | null;
  arenaVaultV1: HexAddress | null;
  arenaAccountFactory: HexAddress | null;
  arenaAccountImplementation: HexAddress | null;
  tableRegistry: HexAddress | null;
  gameRegistry: HexAddress | null;
  sessionLifecycle: HexAddress | null;
  protocolFeeVault: HexAddress | null;
  settlementHub: HexAddress | null;
  settlementHubV1: HexAddress | null;
  /** Explicit V2 hub when settlementHub points at V3 (or null until deploy) */
  settlementHubV2: HexAddress | null;
  /** WP-063 FinalSettlementV3 hub (null until deploy) */
  settlementHubV3: HexAddress | null;
  /** WP-063 VerifierRouter */
  verifierRouter: HexAddress | null;
  /** WP-063 SignatureQuorumVerifier */
  signatureQuorumVerifier: HexAddress | null;
  checkpointRegistry: HexAddress | null;
  randomnessCoordinator: HexAddress | null;
  randomnessBeacon: HexAddress | null;
  /** WP-053 Chainlink VRF v2.5 adapter (null until Sepolia deploy) */
  chainlinkVrfAdapter: HexAddress | null;
  /** WP-062 global proof-batch registry (null until deploy) */
  proofBatchRegistry: HexAddress | null;
  feeTreasury: HexAddress | null;
  deploymentBlock: bigint;
  protocolVersion: string;
  /** Chainlink VRF v2.5 coordinator — verify before deploy */
  vrfCoordinator: HexAddress | null;
  vrfKeyHash: `0x${string}` | null;
};

export const chainManifest = {
  anvil: {
    chainId: 31337,
    usdc: "0xB822ae2d69609853fE92b3428823B1c54dd2D994" as HexAddress,
    symbol: "mUSDC",
    decimals: 6,
    isTestAsset: true,
    faucetEnabled: true,
    arenaVault: "0xB11F73Ac64dbd8846D58Ee80276918204287Db7C" as HexAddress,
    arenaVaultV1: "0x7d310C7c52794BCd2aFD9370bD3FaefbFC281334" as HexAddress,
    arenaAccountFactory: "0x121535645cA1C4cC0A91Bf388CAfe9083fE9Da4E" as HexAddress,
    arenaAccountImplementation: "0xbDE251165b9b7D33f61C9A37f6Ff07c48B4463b2" as HexAddress,
    tableRegistry: "0xf7763831840aE7Cb1A1E7332dc244d18D1C74d9D" as HexAddress,
    gameRegistry: "0x4987af2e7891311F0C8Cab16482Ea40Ed17128E3" as HexAddress,
    sessionLifecycle: "0xE8f2AF7f6b83D2FefC3bc35725eE844124EcF1e5" as HexAddress,
    protocolFeeVault: "0x2FD0603408D9fD16b69326Be04f76a4E70C05157" as HexAddress,
    settlementHub: "0xDbB10E0493c57aB469Cd5cA7EdE8518AF36B86BD" as HexAddress,
    settlementHubV1: "0x09Ddf93be3641ec482C990c8a65f922bA700d4e8" as HexAddress,
    settlementHubV2: "0xDbB10E0493c57aB469Cd5cA7EdE8518AF36B86BD" as HexAddress,
    settlementHubV3: "0xf30e721ec1eae2c5321490924728abD220511BB2" as HexAddress,
    verifierRouter: "0x5D6aA9e74E579f163DBC0aA969E88Cbd2516Ff34" as HexAddress,
    signatureQuorumVerifier: "0x7910916F1caF0541d963FD6f0Df10EDd16E89f23" as HexAddress,
    checkpointRegistry: "0x6ea37Ec2f16Bc4E41e7d137B576e227d675C6E2f" as HexAddress,
    randomnessCoordinator: "0x5892fE64b5F7Cbc008906294804f491A20A71285" as HexAddress,
    randomnessBeacon: "0x03A7BDF5f363B1A514cd20AFb3E4958ffd431a43" as HexAddress,
    chainlinkVrfAdapter: null,
    proofBatchRegistry: "0x92470a2503A0879d813512c25E36D0f30D95C384" as HexAddress,
    feeTreasury: "0x9a61916C0b312F5cD1150596f117A092166ed1ad" as HexAddress,
    deploymentBlock: BigInt(72715),
    protocolVersion: "2.0.0-anvil",
    vrfCoordinator: null,
    vrfKeyHash: null,
  },
  baseSepolia: {
    chainId: 84532,
    usdc: "0x036CbD53842c5426634e7929541eC2318f3dCF7e" as HexAddress,
    symbol: "USDC",
    decimals: 6,
    isTestAsset: false,
    faucetEnabled: false,
    arenaVault: null,
    arenaVaultV1: null,
    arenaAccountFactory: null,
    arenaAccountImplementation: null,
    tableRegistry: null,
    gameRegistry: null,
    sessionLifecycle: null,
    protocolFeeVault: null,
    settlementHub: null,
    settlementHubV1: null,
    settlementHubV2: null,
    settlementHubV3: null,
    verifierRouter: null,
    signatureQuorumVerifier: null,
    checkpointRegistry: null,
    randomnessCoordinator: null,
    randomnessBeacon: null,
    chainlinkVrfAdapter: null,
    proofBatchRegistry: null,
    feeTreasury: null,
    deploymentBlock: BigInt(0),
    protocolVersion: "2.0.0-sepolia",
    vrfCoordinator: "0x5C210eF41CD1a72de73bF76eC39637bB0d3d7BEE" as HexAddress,
    vrfKeyHash: "0x9e1344a1247c8a1785d0a4681a27152bffdb43666ae5bf7d14d24a5efd44bf71" as `0x${string}`,
  },
  base: {
    chainId: 8453,
    usdc: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913" as HexAddress,
    symbol: "USDC",
    decimals: 6,
    isTestAsset: false,
    faucetEnabled: false,
    arenaVault: null,
    arenaVaultV1: null,
    arenaAccountFactory: null,
    arenaAccountImplementation: null,
    tableRegistry: null,
    gameRegistry: null,
    sessionLifecycle: null,
    protocolFeeVault: null,
    settlementHub: null,
    settlementHubV1: null,
    settlementHubV2: null,
    settlementHubV3: null,
    verifierRouter: null,
    signatureQuorumVerifier: null,
    checkpointRegistry: null,
    randomnessCoordinator: null,
    randomnessBeacon: null,
    chainlinkVrfAdapter: null,
    proofBatchRegistry: null,
    feeTreasury: null,
    deploymentBlock: BigInt(0),
    protocolVersion: "2.0.0-mainnet-restricted",
    vrfCoordinator: "0xd5D517aBE5cF79B7e95eC98dB0f0277788aFF634" as HexAddress,
    vrfKeyHash: "0x00b81b5a830cb0a4009fbd8904de511e28631e62ce5ad231373d3cdad373ccab" as `0x${string}`,
  },
} as const satisfies Record<NetworkKey, ChainManifestEntry>;
